---
- hosts: raspberry_pi
  become: true
  tasks:
    # Oppdater pakkelisten og oppgrader systemet
    - name: Oppdater pakkelisten og oppgrader systemet
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600    
    # Installerer nødvendige avhengigheter
    - name: Installer nødvendige avhengigheter
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    # Opprett swap-fil
    - name: Opprett swap-fil
      command: fallocate -l 1G /swapfile
    # Sett riktig tillatelser på swap-filen
    - name: Sett riktig tillatelser på swap-filen
      file:
        path: /swapfile
        mode: '0600'
    # Init swap-filen
    - name: Init swap-filen
      command: mkswap /swapfile
    # Aktiver swap-filen
    - name: Aktiver swap-filen
      command: swapon /swapfile
    # Endre SSH-port til 2222
    - name: Endre SSH-port til 2222
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 2222'
        state: present
    # Deaktiver passordinnlogging
    - name: Deaktiver passordinnlogging
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
    # Start SSH på nytt for å bruke ny konfigurasjon
    - name: Start SSH på nytt
      service:
        name: ssh
        state: restarted
    # Installer Docker
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
    # Start Docker-tjenesten
    - name: Start Docker-tjenesten
      systemd:
        name: docker
        enabled: yes
        state: started
    # Installer Docker Compose
    - name: Last ned Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-armv7l
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    # Bekreft Docker Compose installasjonen
    - name: Sjekk Docker Compose-versjonen
      command: docker-compose --version
