---
- hosts: raspberry_pi
  become: true
  tasks:

    # Update package list and upgrade the system
    - name: Update package list and upgrade system
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    # Install necessary dependencies
    - name: Install necessary dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Create a swap file
    - name: Create swap file
      command: fallocate -l 1G /swapfile

    # Set correct permissions on the swap file
    - name: Set correct permissions on the swap file
      file:
        path: /swapfile
        mode: '0600'

    # Initialize the swap file
    - name: Initialize the swap file
      command: mkswap /swapfile

    # Activate the swap file
    - name: Activate the swap file
      command: swapon /swapfile

    # Change SSH port to 2222
    - name: Change SSH port to 2222
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 2222'
        state: present

    # Disable password authentication
    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    # Restart SSH service to apply the new configuration
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Start Docker service
    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    # Download Docker Compose
    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-armv7l
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Verify Docker Compose installation
    - name: Verify Docker Compose installation
      command: docker-compose --version
