---
- hosts: raspberry_pi
  become: true
  tasks:
    # Oppdater pakkelisten og oppgrader systemet
    - name: Oppdater pakkelisten og oppgrader systemet
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    # Installerer nødvendige avhengigheter
    - name: Installer nødvendige avhengigheter
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    # Opprett swap-fil
    - name: Opprett swap-fil
      command: fallocate -l 1G /swapfile

    # Sett riktig tillatelser på swap-filen
    - name: Sett riktig tillatelser på swap-filen
      file:
        path: /swapfile
        mode: '0600'

    # Init swap-filen
    - name: Init swap-filen
      command: mkswap /swapfile

    # Aktiver swap-filen
    - name: Aktiver swap-filen
      command: swapon /swapfile